"""aggiunta eventi ricorrenti

Revision ID: 422ec0c97a69
Revises: 82f6111a46e4
Create Date: 2026-06-28 18:51:40.147279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '422ec0c97a69'
down_revision: Union[str, Sequence[str], None] = '82f6111a46e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE TABLE IF NOT EXISTS eventi_ricorrenti (id SERIAL PRIMARY KEY, gruppo_id INTEGER NOT NULL REFERENCES gruppi(id), tipo tipoeventoenum NOT NULL DEFAULT 'allenamento', titolo VARCHAR NOT NULL, ora_inizio TIME, ora_fine TIME, luogo VARCHAR, giorni_settimana VARCHAR NOT NULL, data_inizio DATE NOT NULL, data_fine DATE NOT NULL, attivo BOOLEAN DEFAULT TRUE)")
    op.create_index(op.f('ix_eventi_ricorrenti_id'), 'eventi_ricorrenti', ['id'], unique=False)
    op.add_column('eventi', sa.Column('ricorrente_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'eventi', 'eventi_ricorrenti', ['ricorrente_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'eventi', type_='foreignkey')
    op.drop_column('eventi', 'ricorrente_id')
    op.drop_index(op.f('ix_eventi_ricorrenti_id'), table_name='eventi_ricorrenti')
    op.drop_table('eventi_ricorrenti')
    # ### end Alembic commands ###
