"""estensione tesserato con genitore e documenti

Revision ID: 755a2aa7ebcc
Revises: 9b4514b6c924
Create Date: 2026-06-30 21:18:05.036229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '755a2aa7ebcc'
down_revision: Union[str, Sequence[str], None] = '9b4514b6c924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genitori',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cognome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('documento_tipo', sa.String(), nullable=True),
    sa.Column('documento_numero', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genitori_id'), 'genitori', ['id'], unique=False)
    op.create_table('documenti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tesserato_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('nome_file', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('data_scadenza', sa.Date(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tesserato_id'], ['tesserati.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documenti_id'), 'documenti', ['id'], unique=False)
    op.add_column('tesserati', sa.Column('sesso', sa.String(length=1), nullable=True))
    op.add_column('tesserati', sa.Column('email', sa.String(), nullable=True))
    op.add_column('tesserati', sa.Column('cellulare', sa.String(), nullable=True))
    op.add_column('tesserati', sa.Column('comune_nascita', sa.String(), nullable=True))
    op.add_column('tesserati', sa.Column('provincia_nascita', sa.String(), nullable=True))
    op.add_column('tesserati', sa.Column('stato_nascita', sa.String(), nullable=True))
    op.add_column('tesserati', sa.Column('comune_residenza', sa.String(), nullable=True))
    op.add_column('tesserati', sa.Column('provincia_residenza', sa.String(), nullable=True))
    op.add_column('tesserati', sa.Column('regione_residenza', sa.String(), nullable=True))
    op.add_column('tesserati', sa.Column('cap_residenza', sa.String(), nullable=True))
    op.add_column('tesserati', sa.Column('cod_tessera', sa.String(), nullable=True))
    op.add_column('tesserati', sa.Column('tipo_tessera', sa.String(), nullable=True))
    op.add_column('tesserati', sa.Column('categoria', sa.String(), nullable=True))
    op.add_column('tesserati', sa.Column('qualifica', sa.String(), nullable=True))
    op.add_column('tesserati', sa.Column('sport', sa.String(), nullable=True))
    op.add_column('tesserati', sa.Column('data_emissione_tessera', sa.Date(), nullable=True))
    op.add_column('tesserati', sa.Column('data_scadenza_tessera', sa.Date(), nullable=True))
    op.add_column('tesserati', sa.Column('matricola', sa.String(), nullable=True))
    op.add_column('tesserati', sa.Column('disabile', sa.Boolean(), nullable=True))
    op.add_column('tesserati', sa.Column('straniero', sa.Boolean(), nullable=True))
    op.add_column('tesserati', sa.Column('titolo_studio', sa.String(), nullable=True))
    op.add_column('tesserati', sa.Column('foto_url', sa.String(), nullable=True))
    op.drop_constraint(op.f('tesserati_genitore_id_fkey'), 'tesserati', type_='foreignkey')
    op.create_foreign_key(None, 'tesserati', 'genitori', ['genitore_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tesserati', type_='foreignkey')
    op.create_foreign_key(op.f('tesserati_genitore_id_fkey'), 'tesserati', 'tesserati', ['genitore_id'], ['id'])
    op.drop_column('tesserati', 'foto_url')
    op.drop_column('tesserati', 'titolo_studio')
    op.drop_column('tesserati', 'straniero')
    op.drop_column('tesserati', 'disabile')
    op.drop_column('tesserati', 'matricola')
    op.drop_column('tesserati', 'data_scadenza_tessera')
    op.drop_column('tesserati', 'data_emissione_tessera')
    op.drop_column('tesserati', 'sport')
    op.drop_column('tesserati', 'qualifica')
    op.drop_column('tesserati', 'categoria')
    op.drop_column('tesserati', 'tipo_tessera')
    op.drop_column('tesserati', 'cod_tessera')
    op.drop_column('tesserati', 'cap_residenza')
    op.drop_column('tesserati', 'regione_residenza')
    op.drop_column('tesserati', 'provincia_residenza')
    op.drop_column('tesserati', 'comune_residenza')
    op.drop_column('tesserati', 'stato_nascita')
    op.drop_column('tesserati', 'provincia_nascita')
    op.drop_column('tesserati', 'comune_nascita')
    op.drop_column('tesserati', 'cellulare')
    op.drop_column('tesserati', 'email')
    op.drop_column('tesserati', 'sesso')
    op.drop_index(op.f('ix_documenti_id'), table_name='documenti')
    op.drop_table('documenti')
    op.drop_index(op.f('ix_genitori_id'), table_name='genitori')
    op.drop_table('genitori')
    # ### end Alembic commands ###
