"""schema iniziale

Revision ID: 82f6111a46e4
Revises: 
Create Date: 2026-06-26 18:48:01.398049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82f6111a46e4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assemblee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titolo', sa.String(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('ora', sa.Time(), nullable=True),
    sa.Column('luogo', sa.String(), nullable=True),
    sa.Column('stato', sa.Enum('pianificata', 'conclusa', 'annullata', name='statoassembleaenum'), nullable=False),
    sa.Column('path_verbale', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assemblee_id'), 'assemblee', ['id'], unique=False)
    op.create_table('gruppi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descrizione', sa.String(), nullable=True),
    sa.Column('attivo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gruppi_id'), 'gruppi', ['id'], unique=False)
    op.create_table('movimenti_contabili',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('entrata', 'uscita', name='tipomovimentoenum'), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('importo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descrizione', sa.String(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('centro_costo', sa.String(), nullable=True),
    sa.Column('intestatario', sa.String(), nullable=True),
    sa.Column('allegato', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimenti_contabili_id'), 'movimenti_contabili', ['id'], unique=False)
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cognome', sa.String(), nullable=False),
    sa.Column('data_nascita', sa.Date(), nullable=False),
    sa.Column('codice_fiscale', sa.String(length=16), nullable=False),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('ruolo', sa.String(), nullable=False),
    sa.Column('tipo_rapporto', sa.Enum('volontario', 'cococo', 'altro', name='tiporapportoenum'), nullable=False),
    sa.Column('data_inizio', sa.Date(), nullable=False),
    sa.Column('data_fine', sa.Date(), nullable=True),
    sa.Column('attivo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codice_fiscale')
    )
    op.create_index(op.f('ix_staff_id'), 'staff', ['id'], unique=False)
    op.create_table('tariffe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('importo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('attiva', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tariffe_id'), 'tariffe', ['id'], unique=False)
    op.create_table('utenti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('ruolo', sa.Enum('amministratore', 'staff', 'commercialista', 'tesserato', 'genitore', name='ruoloenum'), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utenti_email'), 'utenti', ['email'], unique=True)
    op.create_index(op.f('ix_utenti_id'), 'utenti', ['id'], unique=False)
    op.create_table('compensi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('importo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_erogazione', sa.Date(), nullable=False),
    sa.Column('descrizione', sa.String(), nullable=True),
    sa.Column('path_autocertificazione', sa.String(), nullable=True),
    sa.Column('totale_progressivo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('soglia_superata', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compensi_id'), 'compensi', ['id'], unique=False)
    op.create_table('contratti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('sportivo', 'amministrativo', name='tipocontrattoenum'), nullable=False),
    sa.Column('data_inizio', sa.Date(), nullable=False),
    sa.Column('data_fine', sa.Date(), nullable=True),
    sa.Column('importo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('path_pdf', sa.String(), nullable=True),
    sa.Column('firmato', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contratti_id'), 'contratti', ['id'], unique=False)
    op.create_table('eventi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gruppo_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('allenamento', 'partita', 'raduno', 'altro', name='tipoeventoenum'), nullable=False),
    sa.Column('titolo', sa.String(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('ora_inizio', sa.Time(), nullable=True),
    sa.Column('ora_fine', sa.Time(), nullable=True),
    sa.Column('luogo', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['gruppo_id'], ['gruppi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventi_id'), 'eventi', ['id'], unique=False)
    op.create_table('punti_ordine_giorno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assemblea_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('titolo', sa.String(), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('esito', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assemblea_id'], ['assemblee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_punti_ordine_giorno_id'), 'punti_ordine_giorno', ['id'], unique=False)
    op.create_table('staff_gruppo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('gruppo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gruppo_id'], ['gruppi.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_gruppo_id'), 'staff_gruppo', ['id'], unique=False)
    op.create_table('tesserati',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utente_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cognome', sa.String(), nullable=False),
    sa.Column('data_nascita', sa.Date(), nullable=False),
    sa.Column('codice_fiscale', sa.String(length=16), nullable=False),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('indirizzo', sa.String(), nullable=True),
    sa.Column('e_socio', sa.Boolean(), nullable=True),
    sa.Column('attivo', sa.Boolean(), nullable=True),
    sa.Column('genitore_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genitore_id'], ['tesserati.id'], ),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codice_fiscale')
    )
    op.create_index(op.f('ix_tesserati_id'), 'tesserati', ['id'], unique=False)
    op.create_table('gruppo_tesserato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gruppo_id', sa.Integer(), nullable=False),
    sa.Column('tesserato_id', sa.Integer(), nullable=False),
    sa.Column('data_iscrizione', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['gruppo_id'], ['gruppi.id'], ),
    sa.ForeignKeyConstraint(['tesserato_id'], ['tesserati.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gruppo_tesserato_id'), 'gruppo_tesserato', ['id'], unique=False)
    op.create_table('pagamenti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tesserato_id', sa.Integer(), nullable=False),
    sa.Column('tariffa_id', sa.Integer(), nullable=False),
    sa.Column('importo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_scadenza', sa.Date(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('metodo', sa.Enum('contanti', 'bonifico', 'altro', name='metodopagamentoenum'), nullable=True),
    sa.Column('pagato', sa.Boolean(), nullable=True),
    sa.Column('contabile_allegata', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tariffa_id'], ['tariffe.id'], ),
    sa.ForeignKeyConstraint(['tesserato_id'], ['tesserati.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagamenti_id'), 'pagamenti', ['id'], unique=False)
    op.create_table('partecipazioni_assemblea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assemblea_id', sa.Integer(), nullable=False),
    sa.Column('tesserato_id', sa.Integer(), nullable=False),
    sa.Column('presente', sa.Boolean(), nullable=True),
    sa.Column('delega_a_id', sa.Integer(), nullable=True),
    sa.Column('voto', sa.Enum('favorevole', 'contrario', 'astenuto', name='tipovotoenum'), nullable=True),
    sa.ForeignKeyConstraint(['assemblea_id'], ['assemblee.id'], ),
    sa.ForeignKeyConstraint(['delega_a_id'], ['tesserati.id'], ),
    sa.ForeignKeyConstraint(['tesserato_id'], ['tesserati.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partecipazioni_assemblea_id'), 'partecipazioni_assemblea', ['id'], unique=False)
    op.create_table('presenze',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('tesserato_id', sa.Integer(), nullable=False),
    sa.Column('presente', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['evento_id'], ['eventi.id'], ),
    sa.ForeignKeyConstraint(['tesserato_id'], ['tesserati.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presenze_id'), 'presenze', ['id'], unique=False)
    op.create_table('ricevute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pagamento_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('data_emissione', sa.Date(), nullable=False),
    sa.Column('intestatario', sa.String(), nullable=False),
    sa.Column('importo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('path_pdf', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pagamento_id'], ['pagamenti.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_index(op.f('ix_ricevute_id'), 'ricevute', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ricevute_id'), table_name='ricevute')
    op.drop_table('ricevute')
    op.drop_index(op.f('ix_presenze_id'), table_name='presenze')
    op.drop_table('presenze')
    op.drop_index(op.f('ix_partecipazioni_assemblea_id'), table_name='partecipazioni_assemblea')
    op.drop_table('partecipazioni_assemblea')
    op.drop_index(op.f('ix_pagamenti_id'), table_name='pagamenti')
    op.drop_table('pagamenti')
    op.drop_index(op.f('ix_gruppo_tesserato_id'), table_name='gruppo_tesserato')
    op.drop_table('gruppo_tesserato')
    op.drop_index(op.f('ix_tesserati_id'), table_name='tesserati')
    op.drop_table('tesserati')
    op.drop_index(op.f('ix_staff_gruppo_id'), table_name='staff_gruppo')
    op.drop_table('staff_gruppo')
    op.drop_index(op.f('ix_punti_ordine_giorno_id'), table_name='punti_ordine_giorno')
    op.drop_table('punti_ordine_giorno')
    op.drop_index(op.f('ix_eventi_id'), table_name='eventi')
    op.drop_table('eventi')
    op.drop_index(op.f('ix_contratti_id'), table_name='contratti')
    op.drop_table('contratti')
    op.drop_index(op.f('ix_compensi_id'), table_name='compensi')
    op.drop_table('compensi')
    op.drop_index(op.f('ix_utenti_id'), table_name='utenti')
    op.drop_index(op.f('ix_utenti_email'), table_name='utenti')
    op.drop_table('utenti')
    op.drop_index(op.f('ix_tariffe_id'), table_name='tariffe')
    op.drop_table('tariffe')
    op.drop_index(op.f('ix_staff_id'), table_name='staff')
    op.drop_table('staff')
    op.drop_index(op.f('ix_movimenti_contabili_id'), table_name='movimenti_contabili')
    op.drop_table('movimenti_contabili')
    op.drop_index(op.f('ix_gruppi_id'), table_name='gruppi')
    op.drop_table('gruppi')
    op.drop_index(op.f('ix_assemblee_id'), table_name='assemblee')
    op.drop_table('assemblee')
    # ### end Alembic commands ###
