"""aggiunta permessi operatore

Revision ID: 848fc3462d65
Revises: 755a2aa7ebcc
Create Date: 2026-07-02 07:50:30.954628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '848fc3462d65'
down_revision: Union[str, Sequence[str], None] = '755a2aa7ebcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permessi_operatore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utente_id', sa.Integer(), nullable=False),
    sa.Column('sezione', sa.String(), nullable=False),
    sa.Column('abilitato', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permessi_operatore_id'), 'permessi_operatore', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permessi_operatore_id'), table_name='permessi_operatore')
    op.drop_table('permessi_operatore')
    # ### end Alembic commands ###
