"""aggiunta modulo iscrizione online

Revision ID: 957aaca85b47
Revises: 0c2a6d8a9e15
Create Date: 2026-07-06 05:54:04.880440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '957aaca85b47'
down_revision: Union[str, Sequence[str], None] = '0c2a6d8a9e15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('richieste_iscrizione',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('nome_modulo', sa.String(), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_richieste_iscrizione_id'), 'richieste_iscrizione', ['id'], unique=False)
    op.create_index(op.f('ix_richieste_iscrizione_token'), 'richieste_iscrizione', ['token'], unique=True)
    op.create_table('dati_richiesta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modulo_id', sa.Integer(), nullable=False),
    sa.Column('stato', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cognome', sa.String(), nullable=False),
    sa.Column('data_nascita', sa.String(), nullable=False),
    sa.Column('codice_fiscale', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('cellulare', sa.String(), nullable=True),
    sa.Column('indirizzo', sa.String(), nullable=True),
    sa.Column('comune_residenza', sa.String(), nullable=True),
    sa.Column('provincia_residenza', sa.String(), nullable=True),
    sa.Column('cap_residenza', sa.String(), nullable=True),
    sa.Column('comune_nascita', sa.String(), nullable=True),
    sa.Column('provincia_nascita', sa.String(), nullable=True),
    sa.Column('stato_nascita', sa.String(), nullable=True),
    sa.Column('sesso', sa.String(), nullable=True),
    sa.Column('sport', sa.String(), nullable=True),
    sa.Column('genitore_nome', sa.String(), nullable=True),
    sa.Column('genitore_cognome', sa.String(), nullable=True),
    sa.Column('genitore_email', sa.String(), nullable=True),
    sa.Column('genitore_telefono', sa.String(), nullable=True),
    sa.Column('genitore_documento_tipo', sa.String(), nullable=True),
    sa.Column('genitore_documento_numero', sa.String(), nullable=True),
    sa.Column('consenso_privacy', sa.Boolean(), nullable=True),
    sa.Column('data_invio', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['modulo_id'], ['richieste_iscrizione.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dati_richiesta_id'), 'dati_richiesta', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dati_richiesta_id'), table_name='dati_richiesta')
    op.drop_table('dati_richiesta')
    op.drop_index(op.f('ix_richieste_iscrizione_token'), table_name='richieste_iscrizione')
    op.drop_index(op.f('ix_richieste_iscrizione_id'), table_name='richieste_iscrizione')
    op.drop_table('richieste_iscrizione')
    # ### end Alembic commands ###
