"""aggiunta messaggi broadcast

Revision ID: 9b4514b6c924
Revises: 422ec0c97a69
Create Date: 2026-06-30 07:14:32.206950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b4514b6c924'
down_revision: Union[str, Sequence[str], None] = '422ec0c97a69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messaggi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intestazione', sa.String(), nullable=False),
    sa.Column('corpo', sa.Text(), nullable=False),
    sa.Column('data_invio', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messaggi_id'), 'messaggi', ['id'], unique=False)
    op.create_table('messaggi_destinatari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('messaggio_id', sa.Integer(), nullable=False),
    sa.Column('tesserato_id', sa.Integer(), nullable=False),
    sa.Column('letto', sa.Boolean(), nullable=True),
    sa.Column('email_inviata', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['messaggio_id'], ['messaggi.id'], ),
    sa.ForeignKeyConstraint(['tesserato_id'], ['tesserati.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messaggi_destinatari_id'), 'messaggi_destinatari', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messaggi_destinatari_id'), table_name='messaggi_destinatari')
    op.drop_table('messaggi_destinatari')
    op.drop_index(op.f('ix_messaggi_id'), table_name='messaggi')
    op.drop_table('messaggi')
    # ### end Alembic commands ###
